spring:
  application:
    name: oak store
  datasource:
    url: jdbc:postgresql://db:5432/oak_store_db
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.key
          private-key-location: classpath:private.key
